#+title: Batteries Included.
#+date: 3000-01-01
#+categories[]: Art
#+tags[]: Digital_Art, Linux NixOS, Art_for_Beginners
#+series[]: Configuring_Spacemacs



Originally I was considering including this in the *installing spacemacs* post. But ultimately it seemed like it would be better to have that as an independantn post for easier googling. With that said. I am instead going to create a spin off series discussing how I configure spacemacs. Starting with going through the the included customization optitions, and then with follow up posts covering any custom layers or other changes I make.

Luckily it seems like Spacemacs is /extremely/ well documented.
* Look and Feel
After installation I set Spacemacs to use Vim mode by default. There are a few things I need to do though to make it useable for setting up the rest of the configuration. Starting with adding support for the Colemak keyboard layout, and updating the Theming and Fonts to be more usable by me.

*** Colemak

Configuring support for Colemak was super easy. Basically just a matter of adding a single line to my =.spacemacs= and then reloading Emacs. This process was clearly explained *here*(on the layer git page).

add source code block for
     (keyboard-layout :variables
                      kl-layout 'colemak-neio-inverted)

This doesn't use exactly the same bindings as my previous configuration. Whick used *evil-colemak*, but I am going to give it a try for a while before deciding if I need to over ride them.

*** Themes

The next thing to cover it the default theme. Which to be honest, I am not a fan of. To fix this I will be using the *themeimg* layer.
Again installation was supper easy, and well *documented*(link to layer readme). Just a matter of adding another line to =.spacemacs= containg

=theming=.

Customizing the new theme was done in another section of =.spacemacs= called =user-init=. Adding Modus-Vivendi to
=dotspacemacs-themes=. I was able to use the =themeing= package to tune the colors to match my preferred palate.

*** Fonts

The default font size is way to small for me, and I want to switch over to *Iosveka* as fast as possible. So I will set that up next.
First I added =iosevka-comfy= to my NixOS config. Then I used =fc-list | rg iosevka-comfy= to find
the font name. Then I added this to my =.spacemacs=

(defun dotspacemacs/init ()
  (setq-default
   dotspacemacs-default-font '("Iosevka Comfy Wide Motion"
                               :size 18.0
                               :weight normal
                               :width normal
                               )))


*** Helm

I am a long time helm user, and in makes sense to get completion
going as one of the first steps with configuring spacemacs.

* Concerns
- My most major concern is that Emacs feels /noticably/ slower than my previous configuration. Not start up, but the actual running of commands. I think this has something to do with naitive compilation. Whick has been a subject I have been unclear on for a while.
