#+title: Digital Art with NixOS
#+date: 2023-01-15
#+categories[]: Art
#+tags[]: Digital_Art, Linux NixOS, Art_for_Beginners



* TLDR
This article describes how I have configured my Linux workstation using NixOS to learn the basics of digital art. Including installing Krita, and managing it's config files. Configuring a user input devices, and managing completed projects with git.

* Krita
[[https://krita.org/en/][Krita]] is a Free and Open Source drawing program, comparable to Photoshop or ClipStudio Paint. As a total beginner the idea of not having a subscription was really appealing to me. Krita is fully featured and supports all of the major tasks I would need to do. The main issue that I ran into was managing Krita's configuration files. Krita is unsuprisingly managed via it's GUI, and these files are changed each time you change something within Krita. The problem arises with how NixOS, manages these sort of files.

I store all my configuration files in a single [[https://github.com/Iron-Shark/Technonomicon][repository]]. These files are then added to the "Nix Store", a collection of files used by the Nix package manager to build my user environment. With Krita I do this by targeting the files in my configuration repository with NixOS [[https://nixos.wiki/wiki/Home_Manager][Home-Manager]] and telling it where to write the file to.

#+begin_src nix
  home.file."kritarc" = {
    source = ./Krita/kritarc;
    target = ".config/kritarc";
  };
#+end_src

The problem is that since these files are linked to the Nix Store and not my configuration repository, any changes I make to Krita will be overwritten the next time I update or rebuild my system. I got around this by creating script that copies the most recent version of my Krita files into my configuration repository immediately prior to each system rebuild.

#+begin_src nix
home.file."vortex-upgrade.sh" = {
  target = ".config/system-scripts/vortex-upgrade.sh";
  executable = true;
  text = ''
    #!/bin/sh

    cd ~/Projects/Technonomicon/
    cp -f ~/.config/kritarc Machine-Vortex/Que/Krita/kritarc
    cd -
  '';
};
#+end_src

* Wacom Tablet
I use a [[https://estore.wacom.com/en-US/wacom-intuos-pro-l-us-pth860.html][Wacom Intuos Pro]] drawing tablet. I strongly prefer non-screen tablets. As they tend to cause me to hunch over too much. It also affords a much larger drawing surface for a relatively low price. I have paired it with a [[https://www.amazon.com/dp/B081YR2LLP][Parblo Tablet Stand]], which was surprisingly well built. This lets me keep the tablet elevated to encourage shoulder movement, and low enough that I can still reach the top of the drawing area comfortably.

* Pro-Pen
My Intuos came with a [[https://www.amazon.com/Wacom-KP504E-Pro-Pen-Case/dp/B01MS7ZXIJ][Wacom Pro Pen]]. I have made two major changes to it to make it more comfortable. First a set of [[https://www.amazon.com/dp/B0B5Y18Z87][Titanium Nibs]]. These were an immediate and massive improvement for me. I was going through a plastic nib every 1 - 2 days. With a noticeable improvement in comfort and consistency while drawing. The other is the addition of a [[https://www.amazon.com/dp/B0111LLPH8][Plus Ergo Grip]]. When I first started I was having a lot of issues with hand fatigue. This was a little awkward to get used to, but after a few hours was much more comfortable for extended holding than the standard pen.

* MoonLander
The final addition was using the [[https://www.zsa.io/moonlander/][MoonLander]] keyboard, in the halfmoon configuration. I have a custom layout that allows me to easily preform the most common workflow actions.

* Project Management with Git
